<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="P2TansLaptop" failures="1" tests="2" name="Surefire test" time="0.061" errors="0" timestamp="2022-08-06T12:45:21 PDT">
  <testcase classname="com.udacity.catpoint.SecurityTest" name="addition on addition(com.udacity.catpoint.SecurityTest)" time="0.017">
    <failure type="java.lang.AssertionError" message="1+2 should equal 3 expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: 1+2 should equal 3 expected [4] but found [3]
at com.udacity.security@1.0-SNAPSHOT/com.udacity.catpoint.SecurityTest.addition(SecurityTest.java:20)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addition on addition(com.udacity.catpoint.SecurityTest) -->
  <testcase classname="com.udacity.catpoint.SecurityTest" name="test on test(com.udacity.catpoint.SecurityTest)" time="0.019"/>
</testsuite> <!-- Surefire test -->
